# Generated by Django 3.2.7 on 2021-09-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation_Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('author_name', models.CharField(max_length=200)),
                ('geogebra_link', models.CharField(max_length=1000)),
                ('youtube_link', models.CharField(max_length=1000)),
                ('image', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Video_Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('author_name', models.CharField(max_length=200)),
                ('youtube_link', models.CharField(max_length=1000)),
                ('image', models.CharField(max_length=1000)),
            ],
        ),
    ]
