# Generated by Django 3.2.7 on 2021-09-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phyApp', '0002_remove_simulation_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation_project',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
