# Generated by Django 3.2.7 on 2021-09-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phyApp', '0003_simulation_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_project',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
